### ISSUE TITLE
Remove old hashed files

### ISSUE THREAD

**Issue by zslabs** [smysnk/gulp-rev-all#102]
Does this plugin have support for removing older hashed files or would I need to clear that out manually using [del](https://www.npmjs.com/package/del)?

**Comment by joshuabc** [comment]
I'm curious about this as well.

**Comment by hivre** [comment]
The current strategy I use, is to move all files in a temp directory, before revving and placing them in a dist directory. Before each build-task we empty out the dist directory.
That way the dist directory only ever has files for deployment.

**Comment by zslabs** [comment]
@hivre How do you deal with breaks in the chain, using plumber or not? Do you then restore the files in the original location or is your build broke until you restart?

**Comment by hivre** [comment]
Not much of a JS-ninja, so not sure what you mean with breaks in the chain, but here;s my gulp task:

```
gulp.task('build', ['lint', 'html', 'images', 'fonts', 'extras'], () => {
  return gulp.src('.tmp/**/*')
    .pipe(revAll.revision())
    .pipe(gulp.dest('dist'))
    .pipe($.size({title: 'build', gzip: true}));
});
```

I build/minify everything, and then at the very last step revv it and copy it to the dist dir.

**Comment by jameslnewell** [comment]
[gulp-rev-napkin](https://www.npmjs.com/package/gulp-rev-napkin)?

**Comment by aeomer** [comment]
I "rimraf" the target directories before running the revision process. This prevents all kinds of cruft making it to production.

**Comment by zslabs** [comment]
https://github.com/nib-health-funds/gulp-rev-delete-original appears to be a good option, thanks.
