### ISSUE TITLE
No debug output when debug set to true?

### ISSUE THREAD

**Issue by karlvr** [smysnk/gulp-rev-all#104]
With version 0.7.6 I got a lot of output about the references it was finding if I didn't have quiet set to true, so I was expecting similar output.

**Comment by mediafreakch** [comment]
same issue here. I do:

```
revAll = new rev({
    debug: true
});

return gulp.src(assets)
        .pipe(revAll.revision())
        .pipe(gulp.dest('dist'));
```

And no debug output at all... Files get revisioned though.

`gulp-rev-all@0.8.22`
`gulp@3.9.0`

**Comment by mediafreakch** [comment]
Going through the sources I found only 2 places where you can expect a debug output at all. Both occurrences are within the function that searches the files for references to other files (and only if your Regex doesn't exclude some files to be searched within). There is no logging besides that.
