### ISSUE TITLE
PDF + revAll.revision() with dontSearchFile = corrupted files

### ISSUE THREAD

**Issue by deefour** [smysnk/gulp-rev-all#113]
I have a couple PDF files that are in the list of source files passed into gulp-rev-all. I have the following config set to have them skipped

```
dontSearchFile: [ /\.pdf$/ ]
```

When `revAll.revision()` is called, the PDFs in the destination directory end up nearly double the file size of the originals, and when opened are blank inside. Before I dig in deeper or implement a workaround to filter the PDF files out of the sources passed to gulp-rev-all, I'm wondering if there is something obvious I'm missing which is corrupting these files.

**Comment by circlingthesun** [comment]
Yeah, I'm not sure why PDF's get mangled but ```dontSearchFile: [ /.*\.pdf/]``` does the job for me.

**Comment by deefour** [comment]
Thanks, this does seem to be sorted out in master.

**Comment by lukehutton** [comment]
Ran into this bug today, thought my pdf viewer was broken :|
