### ISSUE TITLE
Does not append hash to conditional include of css in index.html

### ISSUE THREAD

**Issue by sheetalkanade** [smysnk/gulp-rev-all#117]

**Comment by smysnk** [comment]
You might need to include a little bit more information.

**Comment by sheetalkanade** [comment]
Here is my sample index.html where the ie.css is included in a condition and that doesnt get hashed.

<head>
  	<link rel="stylesheet" type="text/css" href="resources/css/bootstrap.9219f0f1fcf6f61fcbb2942dacccc3ed.css">
   	<link rel="stylesheet" type="text/css" href="resources/css/nv.d3.a36e441ae333c8fe085d74a847c97330.css"/>
   	<link rel="stylesheet" type="text/css" href="resources/css/ngDialog.min.24cf82c389768be5a05a60ca5872f6eb.css">
	<link rel="stylesheet" type="text/css" href="resources/css/ngDialog-theme-default.min.92346177a86da9200d8debf5dd52914b.css">
	<link rel="stylesheet" href="resources/css/styles.min.83843b9e420abc1fadbb710fcaf7d8a1.css"/>

**Comment by sheetalkanade** [comment]
There was an issue with my file processing logic so this file was not getting picked. Once I resolved that the file was processed as expected by gulp-rev-all. Thanks.
