### ISSUE TITLE
onlyRenameFile instead of dontRenameFile?

### ISSUE THREAD

**Issue by zerostatic** [smysnk/gulp-rev-all#127]
Instead of excluding files. Is it possible to add something to only include certain files.
For instance if I just want to rev .js and .css files. It would be nice to use something like: 
onlyRenameFile: [".js", ".css"] instead of listing out all the exclude files.

**Comment by smysnk** [comment]
Try this:

dontRenameFile: [ /^((?!\.css|\.js).)*$/ ]

**Comment by zerostatic** [comment]
thanks, that works great!
