### ISSUE TITLE
Wrong MD5 file value on image files.

### ISSUE THREAD

**Issue by hzlzh** [smysnk/gulp-rev-all#129]
``` js
var md5 = function (str) {
        return crypto.createHash('md5').update(str, 'utf8').digest('hex');
    };
```

All the images files' version md5 are wrong, but `.html` and `.js` files is correct.

e.g.
![ff_iconadd 2f035c6776122fc006d96392d2482476](https://cloud.githubusercontent.com/assets/1049575/12373902/c30094fc-bcc5-11e5-94ec-74a77f239a59.png)
Wrong: `2f035c6776122fc006d96392d2482476`
Should be `8c3629a7d6656f24a721c5aa7c8c7f84`

**Comment by wbprice** [comment]
@hzlzh I also ran into this problem.  Did you find a solution?

**Comment by hzlzh** [comment]
Still not
