### ISSUE TITLE
gulp-rev-all is in the black list of http://gulpjs.com/plugins/ ？！

### ISSUE THREAD

**Issue by island205** [smysnk/gulp-rev-all#140]
https://github.com/gulpjs/plugins/blob/master/src/blackList.json#L70

The author of this submition was @sindresorhus, the `gulp-rev`'s author.

The two plugins are totally different, And `gulp-rev-all` is more powerful !

What the fuck, I love this pugin!

**Comment by jemmyzheng** [comment]
@island205 u r right, they are totally different,i think we need open an issue on gulp plugin.

**Comment by island205** [comment]
@jemmyzheng great, please let me kown, i will to give a 👍

**Comment by jemmyzheng** [comment]
@island205 https://github.com/gulpjs/plugins/issues/215,i just opened it.

**Comment by island205** [comment]
@jemmyzheng good work
