### ISSUE TITLE
Architectural change

### ISSUE THREAD

**Issue by damoncasale** [smysnk/gulp-rev-all#154]
Just wanted to chip in that I reopened the issue of gulp-rev-all being on the Blacklist, and got a less biased developer to agree to remove it if a [specific architectural change](https://github.com/gulpjs/plugins/issues/219) is made.  I thought I'd simply refer the matter directly to the gulp-rev-all maintainer to deal with.

Good luck.

**Comment by smysnk** [comment]
Thanks again! Release 9.0 to support required API changes.
