### ISSUE TITLE
0.9 in light of API changes?

### ISSUE THREAD

**Issue by olets** [smysnk/gulp-rev-all#157]
I just read the discussion about gulp team-approved APIs ([part 1](https://github.com/gulpjs/plugins/issues/219), [part 2](https://github.com/gulpjs/plugins/issues/219)). Maybe this isn't a worry, but given that the [cdcad6e API change came with a minor version bump](https://github.com/smysnk/gulp-rev-all/commit/cdcad6e4edb8ac346a37e6cf645604e7b09f08d1) is one appropriate now? I can easily imagine myself updating `gulp-rev-all` without noticing the breaking change if I hadn't happened on that discussion.

**Comment by smysnk** [comment]
It has been updated to 0.9 with the api change.

**Comment by olets** [comment]
Oh, I was looking at the github releases not the npm version, assuming they would be the same. Probably safe to assume everyone's installing via npm so likely doesn't matter that github's latest release binary is 0.8.23 - it just fooled me
