### ISSUE TITLE
BUG: same input should produce same hash

### ISSUE THREAD

**Issue by bitbay** [smysnk/gulp-rev-all#166]
A file with nested file-references ocasionnaly produces different hashes, although none of the files have changed.
Most likely because of the `for...in` at [revisioner.js@L295](https://github.com/smysnk/gulp-rev-all/blob/master/revisioner.js#L295), since `for...in` does not guarantee to loop through the same keys in the same order twice.

I consider this a **bug** - hope You all too.

**Comment by bitbay** [comment]
Have a look at what i tried so far - gives the desired "real-world" result, but breaks the test of "should not change on consecutive runs with no changes"...so still a bummer for me.

**Comment by circlingthesun** [comment]
Did you have a look at https://github.com/smysnk/gulp-rev-all/issues/155 ?

**Comment by bitbay** [comment]
Thank You @circlingthesun, that seems like a more precise definition of what i am experiencing!
Will try gulp-sort ASAP!
