### ISSUE TITLE
Absolute og:image url is not being replaced

### ISSUE THREAD

**Issue by maxstoyanov** [smysnk/gulp-rev-all#168]
I have basically this HTML file:
```html
<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="x-ua-compatible" content="ie=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <meta property="og:title" content="Some description" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="https://url.com/" />
  <meta property="og:image" content="https://url.com/assets/img/opengraph/default.jpg" />
  <meta property="og:description" content="More description" />
  <meta property="fb:app_id" content="4164161684614161" />

  <title>Hello folks!</title>

  <link rel="stylesheet" href="assets/css/site.a990b4a7.css" />
  <base href="/" />

</head>
```

gulp-rev-all correctly replaces all paths in this project but the one in the `og:image` `meta`-tag is revved but not replaced.

This is my dependency tree for gulp-rev-all:
```
+-- gulp-rev-all@0.9.7
| +-- chalk@0.4.0
| | +-- ansi-styles@1.0.0
| | +-- has-color@0.1.7
| | `-- strip-ansi@0.1.1
| +-- gulp-util@2.2.20
| | +-- chalk@0.5.1
| | | +-- ansi-styles@1.1.0
| | | +-- has-ansi@0.1.0
| | | +-- strip-ansi@0.3.0
| | | | `-- ansi-regex@0.2.1
| | | `-- supports-color@0.2.0
| | +-- dateformat@1.0.12
| | +-- lodash._reinterpolate@2.4.1
| | +-- lodash.template@2.4.1
| | | +-- lodash._escapestringchar@2.4.1
| | | +-- lodash.defaults@2.4.1
| | | | `-- lodash._objecttypes@2.4.1
| | | +-- lodash.escape@2.4.1
| | | | +-- lodash._escapehtmlchar@2.4.1
| | | | | `-- lodash._htmlescapes@2.4.1
| | | | `-- lodash._reunescapedhtml@2.4.1
| | | |   `-- lodash.keys@2.4.1
| | | +-- lodash.keys@2.4.1
| | | | +-- lodash._isnative@2.4.1
| | | | +-- lodash._shimkeys@2.4.1
| | | | `-- lodash.isobject@2.4.1
| | | +-- lodash.templatesettings@2.4.1
| | | `-- lodash.values@2.4.1
| | |   `-- lodash.keys@2.4.1
| | +-- minimist@0.2.0
| | +-- through2@0.5.1
| | | `-- xtend@3.0.0
| | `-- vinyl@0.2.3
| +-- merge@1.2.0
| `-- through2@0.4.2
|   +-- readable-stream@1.0.34
|   | `-- isarray@0.0.1
|   `-- xtend@2.1.2
|     `-- object-keys@0.4.0
```

**Comment by circlingthesun** [comment]
Thats because it is a full URL reference. If you change it to an absolute or relative path reference (without the "https://url.com/" bit),  it should work.

**Comment by maxstoyanov** [comment]
I tried this a couple of hours ago and facebook did not like it. It did not find my file... See this SO answer for more details on [Open Graph issues on relative paths](http://stackoverflow.com/a/9858694).

Since I can't change the path to be relative what are my options?

**Comment by circlingthesun** [comment]
@maxstoyanov, I'm not sure. My approach is usually to fork the repo and make it work. Alternatively you could hack something together. Maybe use a relative path and then after gulp-rev-all is done with it you could use something like https://www.npmjs.com/package/gulp-replace to replace `<meta property="og:image" content="` with `<meta property="og:image" content="https://url.com/`.

**Comment by malcolmocean** [comment]
My impression is that you should be able to use `prefix` or `transformPath` for this.

**Comment by guillaumebreux** [comment]
I don't know if this can help but I encountered the same issue and came from with this solution using `gulp-replace` because i din't want to prefix all my urls like `prefix` or `transformPath` would do:

- Add a param url to the image you want an absolute url (e.g. `?absolute=true`)
- Pipe the revision with `.pipe(replace(/"([^"]*)\?absolute=true"/g, "https://yousite.com$1"))`

**Comment by levithomason** [comment]
Though I just hit this same issue, I don't think glup-rev-all should replace the meta og:image content automatically.  Though many sites may host their og:image at the same host as the index.html, it is not always the case.  It may also likely be hosted elsewhere or behind a different CDN.

One proposal might be to allow specifying the host of the index.html.  That way, you can safely know which absolute paths to rewrite.  Any file hosted at the same host as the index.html should be updated.

Feedback?

**Comment by rfgamaral** [comment]
I agree with @levithomason. Still, I needed a workaround for myself and I ended up adding the following `transformPath` function to my `gulp-rev-all` options:

```js
transformPath: (rev, source, path) =>
    rev.includes('unique-og-image-filename') ? `https://domain.com/${rev}` : rev
```

**Working example:** https://github.com/rfgamaral/ricardoamaral.net/commit/fd3606dcc68c8ebd3e9b0b071631b89fea9f9111#diff-ba210a9157252cc983268fdc3aa3ed52R147
