### ISSUE TITLE
if js contain vue, the dist error.

### ISSUE THREAD

**Issue by zhongchengyi** [smysnk/gulp-rev-all#211]
this is the error dist file.
src:
![image](https://user-images.githubusercontent.com/12371940/64147873-5929d800-ce54-11e9-9e80-a3c2f4a21294.png)
dist:
![image](https://user-images.githubusercontent.com/12371940/64147901-6e9f0200-ce54-11e9-9440-5f895b84e736.png)

but ,  if src like 
![image](https://user-images.githubusercontent.com/12371940/64147957-95f5cf00-ce54-11e9-9ab5-b2b3962494ad.png)
the dist is wright..
![image](https://user-images.githubusercontent.com/12371940/64147978-a1e19100-ce54-11e9-868e-77edb1580abf.png)

**Comment by zhongchengyi** [comment]
not only vue, js like this always has the error.
src:
![image](https://user-images.githubusercontent.com/12371940/64148407-d6a21800-ce55-11e9-8101-2f62f2dc7fc9.png)
dist:
![image](https://user-images.githubusercontent.com/12371940/64148416-e28dda00-ce55-11e9-832c-958fddcab779.png)

**Comment by pioug** [comment]
Your case looks similar to the one from the README: https://github.com/smysnk/gulp-rev-all#annotater--replacer
