### ISSUE TITLE
When there are too many files, the MD5 process is slower, how to optimize is better

### ISSUE THREAD

**Issue by longhonour** [smysnk/gulp-rev-all#223]
When the js file exceeds 400, the packaging time reaches more than 4 minutes. How to speed up this process
![image](https://user-images.githubusercontent.com/13929056/144377590-3a92a15e-6159-4d63-a20a-ff0a7a11a4c4.png)
![image](https://user-images.githubusercontent.com/13929056/144378097-3e7e8d32-e7d1-4202-8971-e27f5b607678.png)

**Comment by smysnk** [comment]
Excluding files that are external libraries and not part of your immediate web app would speed things up. Specifically in your screenshot I am seeing that `../project/js/operation/lib` directory.
