### ISSUE TITLE
Different between gulp-rev

### ISSUE THREAD

**Issue by nedelyux** [smysnk/gulp-rev-all#233]
I've started use gulp. Sure i need hash for build files
I've read readme gulp-rev and gulp-rev-all
This Readme has "Consider the following example:" subtitle, but i don't understand what different gulp-rev
Can someone answer me what real problem gulp-rev by real example? And how gulp-rev-all fix it?

**Comment by nedelyux** [comment]
P.S i dont understand what mean re-writing references
I have a css file
It has a background("site.com/public/abc.jpg ")

And if this image is actually replaced but leave the same name (abc.jpg ) then the css file will not change in any way and will be with the same hash

Did I understand correctly?
If this is true, then why is this a problem?
After all, a css file can refer to an image on an external server and we won't know if it's the same image or another one with the same name

Or did I misunderstand the problem that gulp-rev-all solves

**Comment by smysnk** [comment]
It does recursive dependency resolution. If a image referred to in the css file changes, it will change the hash of the css file which refers to the image. This way the css file can also be cached.

There is a scenario where if a css file was cached and image referred to within that css file changed, it will resolve the wrong image.
