### ISSUE TITLE
Src exclusions do not work

### ISSUE THREAD

**Issue by binarykitchen** [smysnk/gulp-rev-all#48]
With this gulp task of mine:

```js
gulp.task('versionize', ['clean:dist', 'build'], function() {
    return gulp.src([
            'build/**',
            '!build/json'
        ])
        .pipe(plugins.revAll({ignore: ['.html']}))
        .pipe(gulp.dest('dist'))
})
```

The `build/json` folder still gets copied over. I do not want the json folder in the destination at all. Do you think you have a test case for this? Probably a bug? Thanks!

**Comment by smysnk** [comment]
This is the result of the files you are trying to ignore are still being emitted and I don't think it's the fault of gulp-rev-all.  Verify gulp.dest() without the plugin does not save the files.
