### ISSUE TITLE
Reflect changes in source maps

### ISSUE THREAD

**Issue by bbrouwer** [smysnk/gulp-rev-all#56]
I love how gulp-rev-all does a terrific job of setting up cache-busting for my app. I also love source maps. Unfortunately, when gulp-rev-all changes my `app.css`, the corresponding `app.css.map` no longer matches the contents of `app.css`. 

It would be nice if gulp-rev-all understood source maps, detecting when a file has a `//# sourceMappingURL=app.js.map` or `/*# sourceMappingURL=app.css.map */` and then update the corresponding app.js.map or app.css.map appropriately.

**Comment by smysnk** [comment]
It would be relatively hard for gulp-rev-all to fix the source maps, an easier solution would be to run gulp-rev-all before code gets minified.

**Comment by bbrouwer** [comment]
I don't think doing what you suggest is reasonable. For example, in my case the app.css is being generated using gulp-less. That would mean that gulp-rev-all would have to be replacing references in the .less files, which I'm pretty sure it doesn't do. Furthermore, at this point, the index.html is not pointing at app.less, it is pointing at app.css. I don't see how I could get gulp-rev-all to correctly rev my index.html. 

As for .js files, I am concatenating a bunch of .js files together into app.js. Again, index.html references app.js, which doesn't event exist at the point you suggest running gulp-rev-all. So again, index.html won't correctly replace the reference to app.js. 

Or if you are suggesting that I do all the concatenation and less compilation first, then run gulp-rev-all, and finally finish up with minification. That also doesn't get me what I'm looking for. I would have to not use source maps for the less compilation and .js concatenation, and then turn on source maps for the final minification step after gulp-rev-all. In this scenario the source maps don't actually reference the original sources anymore. 

There are other ways I have considered to slice and dice this, but none of them actually get me a source map that points to the actual sources in a valid way.

I realize that this is not a trivial request, but it really don't know of a better place to solve this without throwing out gulp-rev-all completely and trying something with gulp-rev. I tried gulp-rev before and gulp-rev-all is a much more complete solution in my opinion.

**Comment by taybin** [comment]
Maybe I'm missing something, but I just wrote a sourceMap fix and submitted a pull request: https://github.com/smysnk/gulp-rev-all/pull/62

**Comment by smysnk** [comment]
Your fix appears to just be for the sourcemap filename, what bbrouwer is requesting is a bit more involved.

**Comment by AlexKey** [comment]
+1

I too would find this a useful feature. gulp-less is generating the sourceMappingURL it would be handy for gulp-rev-all to update it.

**Comment by AlexKey** [comment]
Ah ha, I noticed that the sourceMappingUrl would of worked for me with gulp-less (thanks taybin - nice commit).

But I noticed using https://www.regex101.com/#javascript that it was picking up a trailing space that was output by gulp-sourcemaps

I've made a slight tweak to the sourceMapsRegex to handle trailing spaces #63

**Comment by smysnk** [comment]
v0.8.x should fix these issues, please give it a try.
