### ISSUE TITLE
prefix in amdCommonJs working seems no true

### ISSUE THREAD

**Issue by acelan86** [smysnk/gulp-rev-all#58]
i defined seems

```javascript
define(["js/some"], function () {
});

```
and gulpfile.js

```javascript
gulp.src('**')
    .pipe(revall({
         prefix: "http://cdn.com"
    })
    ...
```

then i get

```javascript
define(["http://cdn.cn/js/some.hash"], function () {
});

```
it no work in requirejs, can not found http://cdn.cn/js/some.hash (no add .js due to requirejs)

so, it's a bug or my mistake?

**Comment by smysnk** [comment]
This should be fixed now, relative references don't get prefixed anymore.
