### ISSUE TITLE
HTML Attributes without quotes are ignored when renaming references.

### ISSUE THREAD

**Issue by brunolazzaro** [smysnk/gulp-rev-all#67]
This is related to #4 and #64. In both cases the solution was to "remove the HTML minification step" which solved the issue. 

After spending some minutes looking into why, i noticed that gulp-minify-html by default removes "redundant quotes" from attributes. So when gulp-rev-all looks into the file, it ignores quoteless attributes. I think this has to do with the `filepathRegex` which i believe does not takes this into account.

To fix this one can add the `quotes: true` parameter to minifyhtml in order to preserve quotes, but i think it might be best to just fix the RegExp.

**Comment by decademoon** [comment]
+1

**Comment by donovanmuller** [comment]
+1

**Comment by albertshaw** [comment]
+1
