### ISSUE TITLE
Incorrect hash used for images referenced in css

### ISSUE THREAD

**Issue by ianks** [smysnk/gulp-rev-all#71]
Working on caching assets for a site, I'm having an issue where the rev'd image filename referenced in the CSS file is different from the _actual_ filename.

The issue exists here: http://d27sc851e8np2m.cloudfront.net/

The image file in the CSS is `header-bg.13100eea.png`, while the valid file is actually https://s3-us-west-2.amazonaws.com/hackcu/img/header-bg.9272b27f.png

Do you know what I could doing wrong?

**Comment by ianks** [comment]
This will be resolved by https://github.com/smysnk/gulp-rev-all/pull/66

**Comment by smysnk** [comment]
Due to large code rewrite, PR closed.  Should be fixed in v0.8.x
