### ISSUE TITLE
Remove duplicate files

### ISSUE THREAD

**Issue by bretthayes** [smysnk/gulp-rev-all#76]
I have separate gulp tasks and the final task is revving the files in my final build folder. I'm ignoring files with the .html extension from being renamed and the references are still hashed which is great. But the problem is that I get both my original files and the hashed files in my final build folder.

For example:
```
/buildFolder
  /assets
    /css
      styles.css
      styles.abc123.css
index.html
```

Is there support for removing the original file after it's hashed and just saving the hashed file?

**Comment by deefour** [comment]
There are quite a few packages to cleanup after after. I use [gulp-rev-napkin](https://www.npmjs.com/package/gulp-rev-napkin).

**Comment by bretthayes** [comment]
@deefour Awesome! This works like a charm. Thanks!
