### ISSUE TITLE
Replace references in non-index.html files?

### ISSUE THREAD

**Issue by sjelfull** [smysnk/gulp-rev-all#80]
Is there a way to specify which files to search through?

All my assets are versioned just fine, but I'm not sure about how to automatically replace the references in .html/.liquid files, which are located different places in the project.

**Comment by smysnk** [comment]
The key word is automatic, it should be doing it already.  Gulp-rev-all works by trying to match all the different relative/absolute path possibilities based on the path of the file being revisioned.

Can you supply some examples of references not getting corrected and their path relation to each other and the base directory of the project.

**Comment by smysnk** [comment]
There are some windows fixes in the the latest release.  If you are a windows user please see if the latest release fixes your issue.

**Comment by sjelfull** [comment]
This is my gulp task:

    var gulp = require('gulp');
    var revall = require('gulp-rev-all');
    var clean = require('gulp-clean');

    gulp.task('cleancdn', function () {
        return gulp.src('public/cdn-assets', {read: false})
            .pipe(clean());
    });

    gulp.task('cdnrev', ['cleancdn'], function () {
        gulp.src('public/assets/dist/**')
            .pipe(revall())
            .pipe(gulp.dest('public/cdn-assets'))
            .pipe(revall.manifest({ fileName: 'manifest.json' }))
            .pipe(gulp.dest('public/cdn-assets'));
    });

A couple of the templates that include references to assets in public/assets/dist folder is located at craft/templates/_layout.html and shopify-templates/theme.liquid.

In theme.liquid, I have these lines:

    <link rel="stylesheet" href="/cdn-assets/css/main.7eb13c78.css" />
    <script src="/cdn-assets/js/all.min.c1a37d5f.js" ></script>

Their references does not include the public path segment, since that's the public web root.

Does that answer your question, @smysnk ?

**Comment by smysnk** [comment]
Why does your template already have revisioned assets?

Also it appears like you are using an older version of gulp-rev-all, please refer to readme for latest usage.

**Comment by sjelfull** [comment]
Because I manually placed and updates them in the templates.

I'll update to the latest version to see if that changes the situation.
