### ISSUE TITLE
Prefix is added to relative URLs

### ISSUE THREAD

**Issue by santiagoaguiar** [smysnk/gulp-rev-all#83]
Using 0.8.12, when I have a css with relative urls:

    background-image: url(foo/bar.png)

and I use the `prefix` option, the rewritten url looks like `url(<prefix>foo/bar)`, while prefix shouldn't be added in this case, or if it is, it should first resolve the absolute URL and then prepend `<prefix>`.

It works ok with 0.7.6, so I rollbacked. I'm not sure I'll get time soon to debug this one.

**Comment by smysnk** [comment]
> while prefix shouldn't be added in this case
Sorry, I am particular familiar with prefix this use-case as I haven't needed to use it in my own projects.   Why shouldn't it be added?

Also, why should it resolve back to absolute url?

**Comment by santiagoaguiar** [comment]
I'm using `prefix` for what's shown on the examples, to provide a URL that points to a cloudfront distribution domain. My prefix is something like `http://1234.cloudfront.net/`. 

I also have html files that I add to `ignore` so they are not renamed (though they are rewritten), that point to css files that will get rewritten, but without specifying the cloudfront domain. This makes it easy to disable cloudfront, or use it over another distribution, etc.

So, if the html points to `foo/bar/file.css`, that file will get renamed to `foo/bar/file.css.xxxx`,and the html file will be updated to point to `<prefix>/foo/bar/file.css.xxxx`. 

But, if `file.css` contains:

    background-image: url(images/img.png)

Pointing to an image at `foo/bar/images/img.png`, that route should either:

* Don't get the prefix, so that when dowloading the `file.css.xxxx`. from `<prefix>/foo/bar/` it will be automatically resolved by following the relative route
* Get the prefix but _also_ the absolute path to it, that is, it should look like: `<prefix>/foo/bar/images.img.png`

Now it's getting rewritten to `<prefix>/images/img.png`, which doesn't work.

And by the way, thanks for this awesome project! :)

**Comment by smysnk** [comment]
Alright I think I understand this now.  Relative references should not be prefixed, absolute references should be prefixed.  

One potential use-case I can see that is not accounted for; that is, people always want their urls prefixed.  That would mean relative references would need to be resolved to absolute locations.

I have published v0.8.13 which has this new logic in here and updated the tests.  Let me know if this works for you.
