### ISSUE TITLE
Can't resolve absolute path

### ISSUE THREAD

**Issue by zensh** [smysnk/gulp-rev-all#84]
```html
<link href="/static/css/lib.css" rel="stylesheet">
<link href="/static/css/app.css" rel="stylesheet">
```

```coffee
gulp.task('revall', ->
  revAll = new RevAll({
    debug: true
    prefix: config.cdnPrefix
    dontGlobal: [/\/favicon\.ico$/]
    dontRenameFile: [/\.html$/]
  })
  merge2([
    gulp.src([
      'public/tmp/views/**'
      'public/tmp/static/fonts/**'
      'public/tmp/static/images/**'
    ], {base: 'public/tmp'}),
    gulp.src([
      'public/tmp/static/js/app.js'
      'public/tmp/static/js/lib.js'
    ], {base: 'public/tmp'}),
    gulp.src([
      'public/tmp/static/css/app.css'
      'public/tmp/static/css/lib.css'
    ], {base: 'public/tmp'}).pipe(minifyCss({keepSpecialComments: 0}))
  ])
  .pipe(revAll.revision())
  .pipe(gulp.dest('public/dist'))
)
```

0.7.X work well with absolute path
0.8.x can't replace absolute path with new reference

While I change path:
```html
<link href="../../static/css/lib.css" rel="stylesheet">
<link href="../../static/css/app.css" rel="stylesheet">
```
It is replaced, but it is not what I need.

**Comment by smysnk** [comment]
I have identified an issue with gulp-rev-all when the `base` options is used with gulp.src.  The latest version v0.8.14 should fix this, let me know if it works better for you.

That said, Gulp-rev-all should auto detect the base and it shouldn't be necessary to use the `base` option.

**Comment by zensh** [comment]
I remove `base` and change `options`:

```coffee
gulp.task('revall', ->
  revAll = new RevAll({
    prefix: config.cdnPrefix
    dontGlobal: [/\/favicon\.ico$/]
    dontRenameFile: [/\.html$/]
    dontUpdateReference: [/\.html$/]
  })
  merge2([
    gulp.src([
      'public/tmp/views/**'
      'public/tmp/static/fonts/**'
      'public/tmp/static/images/**'
    ]),
    gulp.src([
      'public/tmp/static/js/app.js'
      'public/tmp/static/js/lib.js'
    ]),
    gulp.src([
      'public/tmp/static/css/app.css'
      'public/tmp/static/css/lib.css'
    ]).pipe(minifyCss({keepSpecialComments: 0}))
  ])
  .pipe(revAll.revision())
  .pipe(gulp.dest('public/dist'))
)
```

It works, but create some empty dir that from `images`, `views` dir
![qq20150409-1 2x](https://cloud.githubusercontent.com/assets/863754/7061843/4e4480f4-dec9-11e4-98e8-7b15ed0857e3.png)

**Comment by smysnk** [comment]
Sorry can you clarify which are the empty directories getting created?

**Comment by zensh** [comment]
`views` and `static` are that I need, others are unnecessary, and should not be created.

**Comment by smysnk** [comment]
Personally I don't think the directory creation is the work of the plugin, but I could be wrong.

**Comment by malcolmocean** [comment]
I had an issue similar to this one, and [rolled my own solution](https://github.com/malcolmocean/gulp-rev-all) that allows stripping of the root prefix rather than using a separate base or cwd.

Highly possible I'm missing something, as I'm pretty new to gulp.
